#!/bin/bash

# looks for the first variable and set name to world when name is empty
name="${1:-world}"

# ${var:-default} replaces var when empty
# ${var:=default} don't replace var, use within echo
# ${var:?error} error if empty or unset

# set log_level to info when log level is empty
log_level="${LOG_LEVEL:-info}"

# echo name and log_level
echo "Hello, $name (log: $log_level)"
